### ISSUE TITLE
some error in your code

### ISSUE THREAD

**Issue by selous123** [paclopes/HungarianGPU#1]
Firstly i want to show my sincerely thanks for your sharing

I find a quiet small error in your code,when i use 
`#define data float`

and make cost matrix as:
3.30000 3.60000 2.70000 1.50000 4.30000 
3.50000 3.60000 4.20000 4.90000 2.10000 
1.20000 2.70000 4.00000 0.90000 1.30000 
2.60000 4.00000 2.60000 2.20000 3.60000 
1.10000 1.80000 1.70000 2.90000 3.20000

and your code trapped in a dead circle.

The problem is in your function `min_reduce1`
and just correct the value `g1` and `g2` to type `data` instead of `int`

**Comment by paclopes** [comment]
You are right. This was corrected. Thanks.
